name: tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.22.x]
        tests: [1, 2, 3, 4, 5, 6]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run Tests 0${{ matrix.tests }}
        run: make run-tests-0${{ matrix.tests }}