name: tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      - name: Run Tests 01
        run: make run-tests-01

      - name: Run Tests 02
        run: make run-tests-02

      - name: Run Tests 03
        run: make run-tests-03

      - name: Run Tests 04
        run: make run-tests-04

      - name: Run Tests 05
        run: make run-tests-05

      - name: Run Tests 06
        run: make run-tests-06